// This is an auto-generated list of strings used in js code for debugging purpose only
module.exports = [
    ' • The contract doesn\'t end within 5 minutes (for tick duration contracts',
    ' • There are less than 2 ticks between the start and end times',
    'A whole new trading experience on a powerful yet easy to use platform.',
    'A word by itself is easy to guess',
    'AM',
    'Account Authenticated',
    'Account access is temporarily limited. Please check your inbox for more details.',
    'Account authentication',
    'Account balance:',
    'Add +/– to define a barrier offset. For example, +0.005 means a barrier that\'s 0.005 higher than the entry spot.',
    'Add another word or two. Uncommon words are better.',
    'Adjust trade parameters',
    'Agree and accept',
    'All-uppercase is almost as easy to guess as all-lowercase',
    'Apply now as a professional investor',
    'Apr',
    'April',
    'Asian Down',
    'Asian Up',
    'Asian options settle by comparing the [_1]last tick[_2] with the average spot over the period.',
    'At reset time, if the spot is in the opposite direction of your prediction, the barrier is reset to that spot.',
    'Audit',
    'Audit Page',
    'Aug',
    'August',
    'Australian Dollar',
    'Authenticate your account now to take full advantage of all payment methods available.',
    'Automated trading at your fingertips. No coding needed.',
    'Average',
    'Avoid dates and years that are associated with you',
    'Avoid recent years',
    'Avoid repeated words and characters',
    'Avoid sequences',
    'Avoid years that are associated with you',
    'Barrier',
    'Barrier change',
    'Binance USD',
    'Binary Coin',
    'Bitcoin',
    'Buy',
    'Buy price',
    'By purchasing the [_1]"Close-Low"[_2] contract, you\'ll win the multiplier times the difference between the [_1]close[_2] and [_1]low[_2] over the duration of the contract.',
    'By purchasing the [_1]"High-Close"[_2] contract, you\'ll win the multiplier times the difference between the [_1]high[_2] and [_1]close[_2] over the duration of the contract.',
    'By purchasing the [_1]"High-Low"[_2] contract, you\'ll win the multiplier times the difference between the [_1]high[_2] and [_1]low[_2] over the duration of the contract.',
    'Call Spread',
    'Capitalization doesn\'t help very much',
    'Cashier disabled',
    'Chart is not available for this underlying.',
    'Charting for this underlying is delayed',
    'Check your connection.',
    'Click OK to proceed.',
    'Click here to open a Financial Account',
    'Click here to open a Gaming account',
    'Click here to open a Real Account',
    'Close',
    'Close time',
    'Close-Low',
    'Common names and surnames are easy to guess',
    'Complete details',
    'Confirm changes',
    'Connecting to server',
    'Continue trading',
    'Contract Confirmation',
    'Contract details',
    'Contract ends',
    'Contract has not started yet',
    'Contract information',
    'Contract period',
    'Contract result',
    'Contract starts',
    'Contract type',
    'Contract will be sold at the prevailing market price when the request is received by our servers. This price may differ from the indicated price.',
    'Crypto',
    'Current',
    'Current time',
    'Dates are often easy to guess',
    'Deal cancel. fee',
    'Dec',
    'December',
    'Demo',
    'Demo Financial',
    'Demo Financial STP',
    'Demo Synthetic',
    'Deposits and withdrawals have been disabled on your account. Please check your email for more details.',
    'Deriv Apps',
    'Digit',
    'Digit Differs',
    'Digit Even',
    'Digit Matches',
    'Digit Odd',
    'Digit Over',
    'Digit Under',
    'Does Not Touch',
    'Duration',
    'End Time',
    'End time',
    'Ends Between',
    'Ends Outside',
    'Entry Spot',
    'Entry spot',
    'Equals',
    'Ether Classic',
    'Ethereum',
    'Euro',
    'Exclude time cannot be for more than 5 years.',
    'Exclude time cannot be less than 6 months.',
    'Excluded from the website until',
    'Exit Spot',
    'Exit spot',
    'Exit spot time',
    'Exit time',
    'Fall',
    'Fall or equal',
    'Feb',
    'February',
    'Fiat',
    'Final price',
    'Financial',
    'Financial STP',
    'Finish',
    'Fr',
    'Friday',
    'Gaming',
    'Go back',
    'Go to statement',
    'Goes Outside',
    'Guide',
    'High',
    'High Barrier',
    'High Tick',
    'High barrier',
    'High, Low and Close',
    'High-Close',
    'High-Low',
    'Higher',
    'Hour',
    'I want to reapply',
    'IDK',
    'If the [_1]exit spot[_2] is equal to either the [_1]Low barrier[_2] or the [_1]High barrier[_2], you don\'t win the payout.',
    'If the [_1]exit spot[_2] is equal to the [_1]barrier[_2] or the <stronm g>new barrier (if a reset occurs)</stronmg>, you don\'t win the payout.',
    'If the [_1]exit spot[_2] is equal to the [_1]barrier[_2], you don\'t win the payout.',
    'If the [_1]last tick[_2] is equal to the average of the ticks, you don\'t win the payout.',
    'If you select "Allow equals", you win the payout if exit spot is higher than or equal to entry spot for "Rise". Similarly, you win the payout if exit spot is lower than or equal to entry spot for "Fall".',
    'If you select "Asian Fall", you will win the payout if the [_1]last tick[_2] is [_1]lower[_2] than the [_1]average[_2] of the ticks.',
    'If you select "Asian Rise", you will win the payout if the [_1]last tick[_2] is [_1]higher[_2] than the [_1]average[_2] of the ticks.',
    'If you select "Differs", you will win the payout if the [_1]last digit[_2] of the last tick is [_1]not the same[_2] as your [_1]prediction[_2].',
    'If you select "Does Not Touch", you win the payout if the market never touches the [_1]barrier[_2] at any time during the [_1]contract period[_2].',
    'If you select "Ends Between", you win the payout if the [_1]exit spot[_2] is strictly higher than the [_1]Low barrier[_2] AND strictly lower than the [_1]High barrier[_2].',
    'If you select "Ends Outside", you win the payout if the [_1]exit spot[_2] is EITHER strictly higher than the [_1]High barrier[_2], OR strictly lower than the [_1]Low barrier[_2].',
    'If you select "Even", you will win the payout if the [_1]last digit[_2] of the last tick is an [_1]even number (i.e., 2, 4, 6, 8, or 0).[_2]',
    'If you select "Fall", you win the payout if the [_1]exit spot[_2] is strictly lower than the [_1]entry spot[_2].',
    'If you select "Falls", you win the payout if the [_1]exit spot[_2] is strictly lower than the [_1]entry spot[_2].',
    'If you select "Goes Outside", you win the payout if the market touches either the [_1]High barrier[_2] or the [_1]Low barrier[_2] at any time during the [_1]contract period[_2].',
    'If you select "Higher", you win the payout if the [_1]exit spot[_2] is strictly higher than the [_1]barrier[_2].',
    'If you select "Lower", you win the payout if the [_1]exit spot[_2] is strictly lower than the [_1]barrier[_2].',
    'If you select "Matches", you will win the payout if the [_1]last digit[_2] of the last tick is the [_1]same[_2] as your [_1]prediction.[_2]',
    'If you select "Odd", you will win the payout if the [_1]last digit[_2] of the last tick is an [_1]odd number (i.e., 1, 3, 5, 7, or 9).[_2]',
    'If you select "Over", you will win the payout if the [_1]last digit[_2] of the last tick is [_1]greater than your prediction.[_2]',
    'If you select "Reset-Call", you win the payout if the exit spot is strictly higher than either the entry spot or the spot at reset time.',
    'If you select "Reset-Put", you win the payout if the exit spot is strictly lower than either the entry spot or the spot at reset time.',
    'If you select "Rise", you win the payout if the [_1]exit spot[_2] is strictly higher than the [_1]entry spot[_2].',
    'If you select "Rises", you win the payout if the [_1]exit spot[_2] is strictly higher than the [_1]entry spot[_2].',
    'If you select "Stays Between", you win the payout if the market stays between (does not touch) either the [_1]High barrier[_2] or the [_1]Low barrier[_2] at any time during the [_1]contract period[_2].',
    'If you select "Touches", you win the payout if the market touches the [_1]barrier[_2] at any time during the [_1]contract period[_2].',
    'If you select "Under", you will win the payout if the [_1]last digit[_2] of the last tick is [_1]less than your prediction.[_2]',
    'If you select "falls", you win the payout if the market price is lower than the [_1]entry spot[_2].',
    'If you select "falls", you win the payout if the market price is lower than the entry spot.',
    'If you select "rises", you win the payout if the market price is higher than the [_1]entry spot[_2].',
    'If you select "rises", you win the payout if the market price is higher than the entry spot.',
    'If you select [_1]"High Tick"[_2], you win the payout if the selected tick is the [_1]highest among the next five ticks[_2].',
    'If you select [_1]"Low Tick"[_2], you win the payout if the selected tick is the [_1]lowest among the next five ticks[_2].',
    'If you select [_1]"Only Downs"[_2], you win the payout if consecutive ticks fall successively after the [_1]entry spot[_2].[_3]No payout if any tick rises or is equal to any of the previous ticks.',
    'If you select [_1]"Only Ups"[_2], you win the payout if consecutive ticks rise successively after the [_1]entry spot[_2].[_3]No payout if any tick falls or is equal to any of the previous ticks.',
    'If you select a <strong>start time</strong> in the future, the <strong>start time</strong> is that which is selected and the <strong>entry spot</strong> is the price in effect at that time.',
    'If you select a <strong>start time</strong> of "Now", the <strong>end time</strong> is the selected number of minutes/hours after the <strong>start time</strong> (if less than one day in duration), or at the end of the trading day (if one day or more in duration).',
    'If you select a specific <strong>end time</strong>, the <strong>end time</strong> is the selected time.',
    'In the EU, financial binary options are only available to professional investors.',
    'Indicates required field',
    'Indicative',
    'Invalid app id',
    'Invalid email address.',
    'Invalid verification code.',
    'Investment',
    'Jan',
    'January',
    'Jul',
    'July',
    'Jun',
    'June',
    'Litecoin',
    'Looking for CFDs? Go to Trader\'s hub',
    'Loss',
    'Low',
    'Low Barrier',
    'Low Tick',
    'Low barrier',
    'Lower',
    'MT5',
    'MT5 withdrawal disabled',
    'MT5 withdrawals have been disabled on your account. Please check your email for more details.',
    'Mar',
    'March',
    'Maximum multiplier of 1000.',
    'Maximum payout',
    'Maximum:',
    'May',
    'Minimum of [_1] characters required.',
    'Minimum:',
    'Minute',
    'Mo',
    'Monday',
    'More information can be found in an email sent to you.',
    'Multi-Collateral',
    'Multiplier',
    'Multiplier Down',
    'Multiplier Up',
    'Multipliers',
    'Names and surnames by themselves are easy to guess',
    'Net profit',
    'Network status',
    'Next',
    'No currency assigned',
    'No currency selected',
    'No need for symbols, digits, or uppercase letters',
    'Not',
    'Note',
    'Nov',
    'November',
    'Now',
    'Oct',
    'October',
    'Offline',
    'Online',
    'Only Downs',
    'Only Ups',
    'Only letters, numbers, space, and hyphen are allowed.',
    'Only letters, numbers, space, and these special characters are allowed: [_1]',
    'Only letters, numbers, space, hyphen, period, and apostrophe are allowed.',
    'Only letters, space, hyphen, period, and apostrophe are allowed.',
    'Open a Financial Account',
    'Open a Real Account',
    'Our classic “drag-and-drop” tool for creating trading bots, featuring pop-up trading charts, for advanced users.',
    'PM',
    'Password should have lower and uppercase English letters with numbers.',
    'Paxos Standard',
    'Payout',
    'Payout range',
    'Percentage',
    'Please [_1]complete your account profile[_2] to lift your withdrawal and trading limits.',
    'Please [_1]log in[_2] or [_3]sign up[_4] to view this page.',
    'Please accept the terms and conditions.',
    'Please complete the [_1]Real Account form[_2] to verify your age as required by the [_3]UK Gambling[_4] Commission (UKGC).',
    'Please complete the [_1]financial assessment form[_2] to lift your withdrawal and trading limits.',
    'Please confirm that you are not a politically exposed person.',
    'Please ensure that you have the Telegram app installed on your device.',
    'Please enter a valid phone number (e.g. +15417541234).',
    'Please reapply once the required criteria has been fulfilled.',
    'Please reload the page',
    'Please select',
    'Please select a valid time.',
    'Please select the checkbox.',
    'Please set the currency of your account.',
    'Please set your [_1]30-day turnover limit[_2] to remove deposit limits.',
    'Please submit your proof of address.',
    'Please submit your proof of identity.',
    'Potential Payout',
    'Potential Profit',
    'Potential payout',
    'Potential profit/loss',
    'Pound Sterling',
    'Predict the direction<br />and purchase',
    'Predictable substitutions like \'@\' instead of \'a\' don\'t help very much',
    'Previous',
    'Profit',
    'Profit/loss',
    'Proof of address',
    'Proof of address expired',
    'Proof of address required',
    'Proof of identity',
    'Proof of identity expired',
    'Proof of identity required',
    'Purchase',
    'Purchase Time',
    'Purchase price',
    'Purchase request sent',
    'Purchase time',
    'Put Spread',
    'Real',
    'Real Financial',
    'Real Financial STP',
    'Real Synthetic',
    'Recent years are easy to guess',
    'Remaining time',
    'Remove deposit limits',
    'Repeats like "aaa" are easy to guess',
    'Repeats like "abcabcabc" are only slightly harder to guess than "abc"',
    'Requires your browser\'s web storage to be enabled in order to function properly. Please enable it or exit private browsing mode.',
    'Resale not offered',
    'Reset Barrier',
    'Reset Call',
    'Reset Put',
    'Reset Time',
    'Reset balance',
    'Reset barrier',
    'Reset time',
    'Return',
    'Reversed words aren\'t much harder to guess',
    'Rise',
    'Rise or equal',
    'STASIS Euro',
    'Sa',
    'Saturday',
    'Search...',
    'Select Asset',
    'Select Trade Type',
    'Select date',
    'Select your market and underlying asset',
    'Select your trade type',
    'Selected tick',
    'Self-exclusion',
    'Sell',
    'Sell at market',
    'Sep',
    'September',
    'Sequences like abc or 6543 are easy to guess',
    'Session duration limit cannot be more than 6 weeks.',
    'Set account currency',
    'Short keyboard patterns are easy to guess',
    'Should be [_1]',
    'Should be a valid number.',
    'Should be between [_1] and [_2]',
    'Should be less than [_1]',
    'Should be more than [_1]',
    'Should start with letter or number, and may contain hyphen and underscore.',
    'Sign out',
    'SmartTrader is unavailable for this account',
    'Sorry, an error occurred while processing your request.',
    'Sorry, but binary options trading is not available in your country.',
    'Sorry, but binary options trading is not available in your financial account.',
    'Sorry, options trading isn’t available in the United Kingdom and the Isle of Man.',
    'Sorry, this feature is available to virtual accounts only.',
    'Spot',
    'Spot time',
    'Spot time (GMT)',
    'Stake',
    'Start time',
    'Stays Between',
    'Step',
    'Straight rows of keys are easy to guess',
    'Su',
    'Sunday',
    'Switch to another account',
    'Synthetic',
    'Target',
    'Tether ERC20',
    'Tether Omni',
    'Tether TRC20',
    'Th',
    'Thank you, we\'ll get back to you within 24 hours',
    'The <strong>contract period</strong> is the period between the <strong>next tick</strong> after the <strong>start time</strong> and the <strong>end time</strong>.',
    'The <strong>end time</strong> is the selected number of minutes/hours after the <strong>start time</strong> (if less than one day in duration), or at the end of the trading day (if one day or more in duration).',
    'The <strong>end time</strong> is the selected number of minutes/hours after the <strong>start time</strong>.',
    'The <strong>entry spot</strong> is the first tick after the contract is processed by our servers.',
    'The <strong>exit spot</strong> is the latest tick at or before the <strong>end time</strong>.',
    'The <strong>start time</strong> is when the contract is processed by our servers and the <strong>entry spot</strong> is the <strong>next tick</strong> thereafter.',
    'The <strong>start time</strong> is when the contract is processed by our servers.',
    'The Average',
    'The [_1]close[_2] is the latest tick at or before the [_1]end time[_2]. If you selected a specific [_1]end time,[_2] the [_1]end time[_2] is the selected time.',
    'The [_1]contract period[_2] is the period between the [_1]first tick[_2] (after start time) and the [_1]end time[_2].',
    'The [_1]end time[_2] is the selected number of minutes/hours after the [_1]start time[_2].',
    'The [_1]exit spot[_2] is the last tick when the contract ends. Contract ends when all ticks rise or fall successively, or when a single tick breaks the predicted pattern.',
    'The [_1]high[_2] is the highest point ever reached by the market during the contract period.',
    'The [_1]low[_2] is the lowest point ever reached by the market during the contract period.',
    'The [_1]start time[_2] begins when the contract is processed by our servers.',
    'The [_1]start time[_2] is when the contract has been processed by our servers and the [_1]entry spot[_2] is the [_1]next tick[_2] thereafter.',
    'The average is the average of the ticks, including the entry spot and the last tick.',
    'The entry spot is the first tick after the contract is processed by our servers.',
    'The reset time is [_1]',
    'The server <a href="[_1]">endpoint</a> is: [_2]',
    'The two passwords that you entered do not match.',
    'There was an error',
    'There was some invalid character in an input field.',
    'This contract is only available on DTrader.[_1][_2]Go to Dtrader[_3] to close or cancel this contract.',
    'This contract is only available on [_1]DTrader[_2].',
    'This contract lost',
    'This contract won',
    'This feature is not relevant to virtual-money accounts.',
    'This field is required.',
    'This is a staging server - For testing purposes only',
    'This is a top-10 common password',
    'This is a top-100 common password',
    'This is a very common password',
    'This is similar to a commonly used password',
    'This page is only available to logged out clients.',
    'This password is on the blacklist',
    'Thursday',
    'Tick',
    'Ticks history returned an empty array.',
    'Time is in the wrong format.',
    'Time out cannot be in the past.',
    'Time out cannot be more than 6 weeks.',
    'Time out must be after today.',
    'Timed out until',
    'Today',
    'Top up error',
    'Top-up successful',
    'Total Cost',
    'Total profit/loss',
    'Touches',
    'Trade the world\'s markets with our popular user-friendly platform.',
    'Trading and deposit disabled',
    'Trading and deposits have been disabled on your account. Kindly [_1]contact customer support[_2] for assistance.',
    'Trading is unavailable at this time.',
    'Transaction ID',
    'Transaction performed by [_1] (App ID: [_2])',
    'True USD',
    'Try our [_1]Synthetic Indices[_2].',
    'Try our other markets.',
    'Tu',
    'Tuesday',
    'US Dollar',
    'USD Coin',
    'USDK',
    'Understood',
    'Unfortunately, this trading platform is not available for EU Deriv account. Please switch to a non-EU account to continue trading.',
    'Unknown OS',
    'Up to [_1] decimal places are allowed.',
    'Use a few words, avoid common phrases',
    'Use a longer keyboard pattern with more turns',
    'Verification code is wrong. Please use the link sent to your email.',
    'View',
    'View chart',
    'Virtual',
    'Waiting for contract settlement.',
    'Waiting for entry tick.',
    'Waiting for exit tick.',
    'We',
    'Wednesday',
    'We’ll update your limits. Click [_1]Agree and accept[_2] to acknowledge that you are fully responsible for your actions, and we are not liable for any addiction or loss.',
    'When you click "OK" you will be excluded from trading on the site until the selected date.',
    'Winning the contract',
    'Withdrawal and trading limits',
    'Withdrawal disabled',
    'Withdrawals have been disabled on your account. Please check your email for more details.',
    'You are offline',
    'You can close this window without interrupting your trade.',
    'You did not change anything.',
    'You have reached the rate limit of requests per second. Please try later.',
    'You have sold this contract at [_1] [_2]',
    'You should enter [_1] characters.',
    'You will be redirected to a third-party website which is not owned by Binary.com.',
    'You win the payout if the market price does not end in the digit you have selected.',
    'You win the payout if the market price ends in the digit you have selected.',
    'Your account is restricted. Kindly [_1]contact customer support[_2] for assistance.',
    'Your application to be treated as a professional client is being processed.',
    'Your changes have been updated.',
    'Your password cannot be the same as your email address.',
    'Your professional client request is [_1]not approved[_2].',
    'Your session duration limit will end in [_1] seconds.',
    'Your trading statistics since [_1].',
    'Your transaction reference is',
    'Your transaction reference number is [_1]',
    'Your virtual balance has been reset.',
    'Your web browser ([_1]) is out of date and may affect your trading experience. Proceed at your own risk. [_2]Update browser[_3]',
    '[_1] and [_2] cannot be the same.',
    '[_1] days [_2] hours [_3] minutes',
    '[_1] has been credited into your Virtual Account: [_2].',
    '[_1]Note[_2]: Asian contracts will be refunded at the purchase price if the contract doesn\'t end within 5 minutes.',
    '[_1]Note[_2]: Digit contracts will be refunded at the purchase price if the contract doesn\'t end within 5 minutes.',
    '[_1]Note[_2]: Ends Between/Ends Outside contracts will be refunded at the purchase price if there are less than 2 ticks between the start and end times.',
    '[_1]Note[_2]: Even/Odd contracts will be refunded at the purchase price if the contract doesn\'t end within 5 minutes.',
    '[_1]Note[_2]: High Tick/Low Tick contracts have a strict duration of five ticks.',
    '[_1]Note[_2]: Higher/Lower contracts will be refunded at the purchase price if there are less than 2 ticks between the start and end times.',
    '[_1]Note[_2]: Over/Under contracts will be refunded at the purchase price if the contract doesn\'t end within 5 minutes.',
    '[_1]Note[_2]: Rise/Fall contracts will be refunded if:',
    '[_1]Note[_2]: Stays Between/Goes Outside Contracts will be refunded at the purchase price if there are less than 2 ticks between the start and end times.',
    '[_1]Note[_2]: Touch/No Touch contracts will be refunded at the purchase price if there are less than 2 ticks between the start and end times.',
    'account',
    'accounts',
    'day',
    'days',
    'hour',
    'hours',
    'including Deal Cancel. Fee',
    'minute',
    'minutes',
    'second',
    'seconds',
    'tick',
    'ticks',
];
